### PR TITLE
switch to open-balena-base:no-systemd

### PR DESCRIPTION
**Pull request by codewithcheese**
- switched base image to `balena/open-balena-base:no-systemd-12.0.1`
- removed systemd service file
- remove systemd requirements from the readme

### CODE REVIEW

**Comment by joshbwlng** [comment]
@codewithcheese Should probably also remove references to systemd and cgroups from the readme as these should no longer be needed.

**Comment by codewithcheese** [comment]
@joshbwlng good point. I have updated the readme.

**Comment by joshbwlng** [comment]
Here is the `docker-compose.yml` that I could use to run this:
```
version: '2.1'

services:
  balena-mdns-publisher:
    image: 'balena/balena-mdns-publisher:build-no-systemd'
    network_mode: host
    volumes:
      - /run/dbus/system_bus_socket:/home/run/dbus/system_bus_socket
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    environment:
      MDNS_TLD: bar.local
      MDNS_SUBDOMAINS: >-
        ["foo", "buz"]
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
      CONFD_BACKEND: 'ENV'
```

Not sure if it's specific to my system, but I would get the following error if I didn't add `/var/run/dbus/system_bus_socket` as a volume (occurs regardless of cgroups version):
```
balena-mdns-publisher_1  | + exec /usr/src/app/bin/balena-mdns-publisher
balena-mdns-publisher_1  | events.js:377
balena-mdns-publisher_1  |       throw er; // Unhandled 'error' event
balena-mdns-publisher_1  |       ^
balena-mdns-publisher_1  | 
balena-mdns-publisher_1  | Error: connect ENOENT /var/run/dbus/system_bus_socket
balena-mdns-publisher_1  |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
balena-mdns-publisher_1  | Emitted 'error' event at:
balena-mdns-publisher_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/dbus-native/index.js:81:10)
balena-mdns-publisher_1  |     at Socket.emit (events.js:400:28)
balena-mdns-publisher_1  |     at emitErrorNT (internal/streams/destroy.js:106:8)
balena-mdns-publisher_1  |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
balena-mdns-publisher_1  |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
balena-mdns-publisher_1  |   errno: -2,
balena-mdns-publisher_1  |   code: 'ENOENT',
balena-mdns-publisher_1  |   syscall: 'connect',
balena-mdns-publisher_1  |   address: '/var/run/dbus/system_bus_socket'
balena-mdns-publisher_1  | }
josh_balena-mdns-publisher_1 exited with code 1
```

**Comment by codewithcheese** [comment]
@joshbwlng yes that looks like a reasonable requirement when running on the docker engine. For balena need to add the label which does the same thing https://github.com/balena-os/balena-supervisor/blob/master/src/compose/utils.ts#L337

I see now its also mentioned in the README https://github.com/balena-io/balena-mdns-publisher/pull/78/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L43

**Review by joshbwlng — APPROVED** [review]

**Comment by ab77** [comment]
@codewithcheese I can confirm this release is broken.

**Pull request merged**
